# Generated by Django 6.0.3 on 2026-04-09 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('revolving_utilization', models.FloatField()),
                ('age', models.IntegerField()),
                ('nb_30_59_days_late', models.IntegerField()),
                ('debt_ratio', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('nb_open_credit_lines', models.IntegerField()),
                ('nb_90_days_late', models.IntegerField()),
                ('nb_real_estate_loans', models.IntegerField()),
                ('nb_60_89_days_late', models.IntegerField()),
                ('nb_dependents', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='credit_scoring.conseiller')),
            ],
        ),
        migrations.CreateModel(
            name='LogAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit_scoring.dossiercredit')),
            ],
        ),
        migrations.CreateModel(
            name='RapportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='credit_scoring.dossiercredit')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('proba_defaut', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='credit_scoring.dossiercredit')),
            ],
        ),
        migrations.CreateModel(
            name='ExplicationSHAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('valeur_shap', models.FloatField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explications', to='credit_scoring.scorerisque')),
            ],
        ),
    ]
